name: Feature request
description: Propose a new feature
title: "[feat] "
labels: [enhancement]
body:
  - type: textarea
    id: context
    attributes:
      label: Context / problem
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - backend
        - frontend
        - docs
        - infra
    validations:
      required: true
